#!/usr/bin/python

from subprocess import call
from sys import argv, stderr, stdout, exit
from os.path import isfile, join, dirname, basename

def err(msg):
    stdout.flush()
    stderr.flush()
    stderr.write('[llvm-slicer-c]: ' + msg + '\n')
    exit(1)

def printcmd(cmd):
    print('> {0}'.format(' '.join(cmd)))

slicer='llvm-slicer'
clang='clang'
link='llvm-link'

###
# Try to find the right path to the slicer
if isfile(slicer):
    slicer='./{0}'.format(slicer)
else:
    d = dirname(argv[0])
    p = join(d, slicer)
    if isfile(p):
        slicer = p

clangcmd=[clang, '-emit-llvm', '-c', '-g']
slicercmd=[slicer]
files=[]

###
# Build the commands
next_is_clang=False
for x in argv[1:]:
    if next_is_clang:
        clangcmd.append(x)
        next_is_clang = False
    elif x == '-Xclang':
        next_is_clang = True
    elif x.endswith('.c') or x.endswith('.cpp') or x.endswith('.i'):
        files.append(x)
    else:
        slicercmd.append(x)

def repl_suffix(fl):
    f = basename(fl)
    if f.endswith('.c') or f.endswith('.i'):
        return '{0}.bc'.format(f[:-2])
    elif f.endswith('.cpp'):
        return '{0}.bc'.format(f[:-4])

if len(files) < 1:
    err('No input files given')

###
# Issue clang to compile sources to bitcode(s)
clangcmd += files
bitcodes = list(map(repl_suffix, files))
bitcode = None

printcmd(clangcmd)
r = call(clangcmd)
if r != 0:
    err('clang command return non-zero status')

###
# Link multiple files if needed
if len(files) > 1:
    bitcode='bitcode.bc'
    linkcmd=[link, '-o', bitcode] + bitcodes

    printcmd(linkcmd)
    r = call(linkcmd)
    if r != 0:
        err('llvm-link command return non-zero status')

else:
    bitcode = bitcodes[0]

###
# Slice the code
slicercmd.append(bitcode)
printcmd(slicercmd)

r = call(slicercmd)
if r != 0:
    err('slicer command return non-zero status')
