#!/bin/bash

#defult program
GUI=xdg-open

if which okular &>/dev/null; then
	GUI=okular
elif which evince &>/dev/null; then
	GUI=evince
fi

`dirname $0`/llvm-ps-dump -dot $@ > _ps.dot && dot -Tpdf -o _ps.pdf _ps.dot && $GUI _ps.pdf
rm _ps.pdf _ps.dot
